import CryptoKit
import Foundation

public enum PasteboardType: String, Sendable, Hashable {
    case plainText = "public.utf8-plain-text"
    case concealed = "org.nspasteboard.ConcealedType"
    case transient = "org.nspasteboard.TransientType"
    case autoGenerated = "org.nspasteboard.AutoGeneratedType"
}

public protocol PasteboardItem: AnyObject {
    var declaredTypes: Set<PasteboardType> { get }
    func readPlainText() -> String?
}

public enum ClipboardVerdict: Equatable, Sendable {
    case candidate(text: String, hashPrefix: String)
    case concealedSkip
    case unsupportedType
    case sizeDrop
    case duplicateDrop(hashPrefix: String)
}

public struct ClipboardCandidateFilter: Sendable {
    public static let maximumBytes = 32 * 1_024
    public static let deduplicationInterval: TimeInterval = 10 * 60

    private var recentlySeen: [String: Date] = [:]

    public init() {}

    public mutating func evaluate(_ item: PasteboardItem, now: Date) -> ClipboardVerdict {
        let types = item.declaredTypes
        if !types.isDisjoint(with: [.concealed, .transient, .autoGenerated]) {
            return .concealedSkip
        }
        guard types.contains(.plainText), let text = item.readPlainText() else {
            return .unsupportedType
        }
        guard text.lengthOfBytes(using: .utf8) <= Self.maximumBytes else {
            return .sizeDrop
        }

        recentlySeen = recentlySeen.filter { now.timeIntervalSince($0.value) < Self.deduplicationInterval }
        let hash = Self.hash(text)
        let prefix = String(hash.prefix(16))
        if recentlySeen[hash] != nil {
            return .duplicateDrop(hashPrefix: prefix)
        }
        recentlySeen[hash] = now
        return .candidate(text: text, hashPrefix: prefix)
    }

    public static func hashPrefix(_ text: String) -> String {
        String(hash(text).prefix(16))
    }

    private static func hash(_ text: String) -> String {
        SHA256.hash(data: Data(text.utf8)).map { String(format: "%02x", $0) }.joined()
    }
}
